"""Add stremio sync watch state

Revision ID: b444a9971f02
Revises: 0006_rule_snapshot_release_cache_columns
Create Date: 2026-04-02 01:29:01.825414
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b444a9971f02"
down_revision = "0006_rule_snapshot_release_cache_columns"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column("stremio_known_episode_numbers", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "rules",
        sa.Column(
            "stremio_watched_episode_numbers", sa.JSON(), nullable=False, server_default="[]"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules",
        sa.Column(
            "quality_exclude_pattern", sa.TEXT(), server_default=sa.text("('')"), nullable=False
        ),
    )
    op.add_column(
        "rules",
        sa.Column(
            "quality_include_pattern", sa.TEXT(), server_default=sa.text("('')"), nullable=False
        ),
    )
    op.alter_column(
        "rules",
        "media_type",
        existing_type=sa.Enum("SERIES", "MOVIE", "AUDIOBOOK", "MUSIC", "OTHER", name="media_type"),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    op.drop_column("rules", "stremio_watched_episode_numbers")
    op.drop_column("rules", "stremio_known_episode_numbers")
    # ### end Alembic commands ###
